baseURL: "https://qutrits.github.io/"
title: <Qutrits/>
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-215417930-1
# disqusShortname: https-qutrits-github-io

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: series
          name: ì‹œë¦¬ì¦ˆ
          url: /series-list/
          weight: 10
        - identifier: collection
          name: ëª¨ì•„ë³´ê¸°
          url: /collection/
          weight: 20
        - identifier: Archive
          name: ê¸°ë¡ ë³´ê´€ì†Œ
          url: /archives/
          weight: 70
        - identifier: Search
          name: ê²€ìƒ‰
          url: /search/
          weight: 80
        - identifier: Tags
          name: íƒœê·¸
          url: /tags/
          weight: 90

# defaultContentLanguage: ko
# languages:
#     ko:
#         languageName: KO ğŸ‡°ğŸ‡·
#         languageAltTitle: Korean
#         weight: 1
#         profileMode:
#             enabled: true
#             title: "ë°˜ê°‘ìŠµë‹ˆë‹¤!"
#             imageUrl: "/icon/profile_pic.png"
#             imageTitle: my image
#             imageWidth: 120
#             imageHeight: 120
#             # subtitle: "ì´ê³³ì€ í•œêµ­ì–´ í˜ì´ì§€ì…ë‹ˆë‹¤."
#             buttons:
#                 - name: ì‹œë¦¬ì¦ˆ
#                   url: series-list
#                 - name: ëª¨ì•„ë³´ê¸°
#                   url: collection
#                 - name: ê¸°ë¡ ë³´ê´€ì†Œ
#                   url: archives
#                 - name: ê²€ìƒ‰
#                   url: search
#                 - name: íƒœê·¸
#                   url: tags
#         menu:
#             main:
#                 - name: ì‹œë¦¬ì¦ˆ
#                   url: series-list
#                   weight: 5
#                 - name: ëª¨ì•„ë³´ê¸°
#                   url: collection
#                   weight: 10
#                 - name: ê¸°ë¡ ë³´ê´€ì†Œ
#                   url: archives
#                   weight: 15
#                 - name: ê²€ìƒ‰
#                   url: search
#                   weight: 20
#                 - name: íƒœê·¸
#                   url: tags
#                   weight: 25
#     en:
#         languageName: EN ğŸ‡ºğŸ‡¸
#         languageAltTitle: English
#         weight: 2
#         profileMode:
#             enabled: true
#             title: "Hello there!"
#             imageUrl: "/icon/profile_pic.png"
#             imageTitle: my image
#             imageWidth: 120
#             imageHeight: 120
#             # subtitle: "Hello, there!"
#             buttons:
#                 # - name: Series
#                 #   url: series-list
#                 # - name: Collection
#                 #   url: collection
#                 - name: Posts
#                   url: posts
#                 - name: Archives
#                   url: archives
#                 - name: Search
#                   url: search
#                 - name: Tags
#                   url: tags
#         menu:
#             main:
#                 # - name: Series
#                 #   url: series-list
#                 #   weight: 5
#                 # - name: Collection
#                 #   url: collection
#                 #   weight: 10
#                 - name: Posts
#                   url: posts
#                   weight: 10
#                 - name: Archives
#                   url: archives
#                   weight: 15
#                 - name: Search
#                   url: search
#                   weight: 20
#                 - name: Tags
#                   url: tags
#                   weight: 25
    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     # title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     menu:
    #         main:
    #             - name: Tags
    #               url: tags
    #               weight: 10
#     fr:
#         languageName: ":fr:"
#         languageAltTitle: French
#         weight: 2
#         title: PaperModL2
#         profileMode:
#             enabled: true
#             title: PaperMod
#             # imageUrl: "#"
#             # imageTitle: my image
#             # imageWidth: 120
#             # imageHeight: 120
#             subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
#             buttons:
#                 - name: Blog
#                   url: posts
#                 - name: Tags
#                   url: tags
#         menu:
#             main:
#                 - name: Archive
#                   url: archives/
#                   weight: 5
#                 - name: Tags
#                   url: tags
#                   weight: 10
#                 - name: Categories
#                   url: categories
#                   weight: 10
#                 - name: Series
#                   url: series
#                   weight: 10
#                 - name: NullLink
#                   url: "#"
#                 - name: NullLink2
#                   url: "#"
#                 - name: NullLink3
#                   url: "#"

params:
    useElementAnimation: true
    # displayFullLangName: true
    useUtterances: true
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # title: ExampleSite
    description: "<Qutrits/>"
    keywords: ["qutrits", "ìë°”", "java"]
    # author: Me
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    # DateFormat: "January 2, 2006"
    # DateFormat: "2006ë…„ 1ì›” 2ì¼"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    GithubRepoUrl: "https://github.com/qutrits/qutrits.github.io"

    ShowFontSizeButton: true
    ShowCreativeCommons: true
    ShowShareButtons: true
    # ShowReadingTime: true
    # ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    # ShowCodeCopyButtons: false
    # disableSpecial1stPost: false
    # disableScrollToTop: true
    # comments: false
    # hidemeta: false
    # hideSummary: false
    # showtoc: false
    # tocopen: false
    # showTocAside: true

    assets:
        useCustomJs: true
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/icon/favicon-64.png"
        favicon16x16: "/icon/favicon-16.png"
        favicon32x32: "/icon/favicon-32.png"
    #   apple_touch_icon: "<link / abs url>"
    #   safari_pinned_tab: "<link / abs url>"

    label:
        text: ""
        icon: /icon/home.webp
        iconHeight: 25
        iconWidth: 25

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "ë°˜ê°‘ìŠµë‹ˆë‹¤."
        # subtitle: "ë°˜ê°‘ìŠµë‹ˆë‹¤."
        imageUrl: "/icon/profile_pic.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
        - name: Posts
          url: posts
        - name: Series
          url: series-list
        - name: Archives
          url: archives
        - name: Tags
          url: tags

    # home-info mode
    # homeInfoParams:
    #   Title: "Hi there \U0001F44B"
    #   Content: Write-ups âœï¸
    #   ProfilePicture: "/icon/profile_pic.png"
    
    socialIcons:
        # - name: twitter
        #   url: "https://twitter.com/"
        # - name: stackoverflow
        #   url: "https://stackoverflow.com"
        - name: email
          url: "mailto:terro21c@gmail.com"
        - name: telegram
          url: "https://t.me/qu_bits"
        - name: github
          url: "https://github.com/qutrits"
        - name: link
          url: "/links"
        # - name: instagram
        #   url: "Put your Instagram url here."
        # - name: twitch
        #   url: "Put your twitch url here."
        # - name: link
        #   url: ""
        - name: rss
          url: "/index.xml"

    # analytics:
    #   google:
    #     SiteVerificationTag: "XYZabc"
    #   bing:
    #     SiteVerificationTag: "XYZabc"
    #   yandex:
    #     SiteVerificationTag: "XYZabc"

    # cover:
    #   hidden: true # hide everywhere but not in structured data
    #   hiddenInList: false # hide on list pages and home
    #   hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/qutrits/qutrits.github.io/blob/main/content"
        # Text: "ìˆ˜ì •ì‚¬í•­ ì œì•ˆ" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

taxonomies:
    series: series
    chapter: chapter
    category: categories
    tag: tags

markup:
    goldmark:
        renderer:
            hardWraps: true
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: true
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true